version: "3"
services:
    api:
        build: .
        depends_on:
            - postgres
        ports:
            - 8000:8000

        volumes: 
            - ./:/usr/src/app:ro

        command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

        #env_file: 
           # - ./.env
           #pass changed just for reference    
        environment:
            - DATABASE_HOSTNAME=postgres
            - DATABASE_PORT=ArzumKuzum2134-
            - DATABASE_PASSWORD=ArzumKuzum2134-
            - DATABASE_NAME=fastapi
            - DATABASE_USERNAME=postgres
            - SECRET_KEY=settings.secret_key
            - ALGORITHM=HS256
            - ACCESS_TOKEN_EXPIRE_TIME=60

    postgres:
      image: postgres
      environment:
          - POSTGRES_PASSWORD=ArzumKuzum2134
          - POSTGRES_DB=fastapi

      volumes:
          - postgres-db:/var/lib/postgresql/data


volumes:
    postgre-db: